/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TowerRouteImport } from './routes/tower'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DocumentsDocIdRouteImport } from './routes/documents/$docId'
import { Route as ExamsIndexRouteImport } from './routes/exams/index'
import { Route as ExamsExamIdRouteImport } from './routes/exams/$examId'
import { Route as GuildsIndexRouteImport } from './routes/guilds/index'
import { Route as GuildsGuildIdRouteImport } from './routes/guilds/$guildId'
import { Route as PvpIndexRouteImport } from './routes/pvp/index'
import { Route as PvpMatchIdRouteImport } from './routes/pvp/$matchId'
import { Route as SurvivalIndexRouteImport } from './routes/survival/index'
import { Route as SurvivalRoomIdRouteImport } from './routes/survival/$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ExamsExamIdIndexRouteImport } from './routes/exams/$examId.index'
import { Route as ExamsExamIdTakeRouteImport } from './routes/exams/$examId.take'
import { Route as ExamsExamIdResultAttemptIdRouteImport } from './routes/exams/$examId.result.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TowerRoute = TowerRouteImport.update({
  id: '/tower',
  path: '/tower',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/documents/$docId',
  path: '/documents/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsIndexRoute = GuildsIndexRouteImport.update({
  id: '/guilds/',
  path: '/guilds/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdRoute = GuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const PvpIndexRoute = PvpIndexRouteImport.update({
  id: '/pvp/',
  path: '/pvp/',
  getParentRoute: () => rootRouteImport,
} as any)
const PvpMatchIdRoute = PvpMatchIdRouteImport.update({
  id: '/pvp/$matchId',
  path: '/pvp/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalIndexRoute = SurvivalIndexRouteImport.update({
  id: '/survival/',
  path: '/survival/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivalRoomIdRoute = SurvivalRoomIdRouteImport.update({
  id: '/survival/$roomId',
  path: '/survival/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdIndexRoute = ExamsExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsExamIdRoute,
} as any)
const ExamsExamIdTakeRoute = ExamsExamIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => ExamsExamIdRoute,
} as any)
const ExamsExamIdResultAttemptIdRoute =
  ExamsExamIdResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => ExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/tower': typeof TowerRoute
  '/tutor': typeof TutorRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/exams/$examId': typeof ExamsExamIdRouteWithChildren
  '/guilds/$guildId': typeof GuildsGuildIdRoute
  '/pvp/$matchId': typeof PvpMatchIdRoute
  '/survival/$roomId': typeof SurvivalRoomIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/guilds/': typeof GuildsIndexRoute
  '/pvp/': typeof PvpIndexRoute
  '/survival/': typeof SurvivalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
  '/exams/$examId/result/$attemptId': typeof ExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/tower': typeof TowerRoute
  '/tutor': typeof TutorRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/guilds/$guildId': typeof GuildsGuildIdRoute
  '/pvp/$matchId': typeof PvpMatchIdRoute
  '/survival/$roomId': typeof SurvivalRoomIdRoute
  '/documents': typeof DocumentsIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/guilds': typeof GuildsIndexRoute
  '/pvp': typeof PvpIndexRoute
  '/survival': typeof SurvivalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/exams/$examId': typeof ExamsExamIdIndexRoute
  '/exams/$examId/result/$attemptId': typeof ExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/tower': typeof TowerRoute
  '/tutor': typeof TutorRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/exams/$examId': typeof ExamsExamIdRouteWithChildren
  '/guilds/$guildId': typeof GuildsGuildIdRoute
  '/pvp/$matchId': typeof PvpMatchIdRoute
  '/survival/$roomId': typeof SurvivalRoomIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/guilds/': typeof GuildsIndexRoute
  '/pvp/': typeof PvpIndexRoute
  '/survival/': typeof SurvivalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
  '/exams/$examId/result/$attemptId': typeof ExamsExamIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forge'
    | '/login'
    | '/profile'
    | '/register'
    | '/shop'
    | '/tower'
    | '/tutor'
    | '/documents/$docId'
    | '/exams/$examId'
    | '/guilds/$guildId'
    | '/pvp/$matchId'
    | '/survival/$roomId'
    | '/documents/'
    | '/exams/'
    | '/guilds/'
    | '/pvp/'
    | '/survival/'
    | '/api/auth/$'
    | '/exams/$examId/take'
    | '/exams/$examId/'
    | '/exams/$examId/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forge'
    | '/login'
    | '/profile'
    | '/register'
    | '/shop'
    | '/tower'
    | '/tutor'
    | '/documents/$docId'
    | '/guilds/$guildId'
    | '/pvp/$matchId'
    | '/survival/$roomId'
    | '/documents'
    | '/exams'
    | '/guilds'
    | '/pvp'
    | '/survival'
    | '/api/auth/$'
    | '/exams/$examId/take'
    | '/exams/$examId'
    | '/exams/$examId/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/forge'
    | '/login'
    | '/profile'
    | '/register'
    | '/shop'
    | '/tower'
    | '/tutor'
    | '/documents/$docId'
    | '/exams/$examId'
    | '/guilds/$guildId'
    | '/pvp/$matchId'
    | '/survival/$roomId'
    | '/documents/'
    | '/exams/'
    | '/guilds/'
    | '/pvp/'
    | '/survival/'
    | '/api/auth/$'
    | '/exams/$examId/take'
    | '/exams/$examId/'
    | '/exams/$examId/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgeRoute: typeof ForgeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  TowerRoute: typeof TowerRoute
  TutorRoute: typeof TutorRoute
  DocumentsDocIdRoute: typeof DocumentsDocIdRoute
  ExamsExamIdRoute: typeof ExamsExamIdRouteWithChildren
  GuildsGuildIdRoute: typeof GuildsGuildIdRoute
  PvpMatchIdRoute: typeof PvpMatchIdRoute
  SurvivalRoomIdRoute: typeof SurvivalRoomIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  GuildsIndexRoute: typeof GuildsIndexRoute
  PvpIndexRoute: typeof PvpIndexRoute
  SurvivalIndexRoute: typeof SurvivalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tower': {
      id: '/tower'
      path: '/tower'
      fullPath: '/tower'
      preLoaderRoute: typeof TowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/': {
      id: '/guilds/'
      path: '/guilds'
      fullPath: '/guilds/'
      preLoaderRoute: typeof GuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId': {
      id: '/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof GuildsGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvp/': {
      id: '/pvp/'
      path: '/pvp'
      fullPath: '/pvp/'
      preLoaderRoute: typeof PvpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvp/$matchId': {
      id: '/pvp/$matchId'
      path: '/pvp/$matchId'
      fullPath: '/pvp/$matchId'
      preLoaderRoute: typeof PvpMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival/': {
      id: '/survival/'
      path: '/survival'
      fullPath: '/survival/'
      preLoaderRoute: typeof SurvivalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survival/$roomId': {
      id: '/survival/$roomId'
      path: '/survival/$roomId'
      fullPath: '/survival/$roomId'
      preLoaderRoute: typeof SurvivalRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/': {
      id: '/exams/$examId/'
      path: '/'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof ExamsExamIdIndexRouteImport
      parentRoute: typeof ExamsExamIdRoute
    }
    '/exams/$examId/take': {
      id: '/exams/$examId/take'
      path: '/take'
      fullPath: '/exams/$examId/take'
      preLoaderRoute: typeof ExamsExamIdTakeRouteImport
      parentRoute: typeof ExamsExamIdRoute
    }
    '/exams/$examId/result/$attemptId': {
      id: '/exams/$examId/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/exams/$examId/result/$attemptId'
      preLoaderRoute: typeof ExamsExamIdResultAttemptIdRouteImport
      parentRoute: typeof ExamsExamIdRoute
    }
  }
}

interface ExamsExamIdRouteChildren {
  ExamsExamIdTakeRoute: typeof ExamsExamIdTakeRoute
  ExamsExamIdIndexRoute: typeof ExamsExamIdIndexRoute
  ExamsExamIdResultAttemptIdRoute: typeof ExamsExamIdResultAttemptIdRoute
}

const ExamsExamIdRouteChildren: ExamsExamIdRouteChildren = {
  ExamsExamIdTakeRoute: ExamsExamIdTakeRoute,
  ExamsExamIdIndexRoute: ExamsExamIdIndexRoute,
  ExamsExamIdResultAttemptIdRoute: ExamsExamIdResultAttemptIdRoute,
}

const ExamsExamIdRouteWithChildren = ExamsExamIdRoute._addFileChildren(
  ExamsExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgeRoute: ForgeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  TowerRoute: TowerRoute,
  TutorRoute: TutorRoute,
  DocumentsDocIdRoute: DocumentsDocIdRoute,
  ExamsExamIdRoute: ExamsExamIdRouteWithChildren,
  GuildsGuildIdRoute: GuildsGuildIdRoute,
  PvpMatchIdRoute: PvpMatchIdRoute,
  SurvivalRoomIdRoute: SurvivalRoomIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  GuildsIndexRoute: GuildsIndexRoute,
  PvpIndexRoute: PvpIndexRoute,
  SurvivalIndexRoute: SurvivalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
